# Generated by Django 3.1.1 on 2023-01-26 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('np1', models.IntegerField()),
                ('np2', models.IntegerField()),
                ('np3', models.IntegerField()),
                ('npa', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('aluno_ra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
                ('disciplina_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disciplina.disciplina')),
            ],
        ),
    ]
