# Generated by Django 3.1.1 on 2023-01-26 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estagio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('ra', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('ano_nascimento', models.IntegerField()),
                ('cpf', models.CharField(max_length=14)),
                ('cidade', models.CharField(max_length=45)),
                ('bairro', models.CharField(max_length=45)),
                ('rua', models.CharField(max_length=45)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=200)),
                ('Estagio_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estagio.estagio')),
            ],
        ),
    ]
